### ISSUE TITLE
Output not correctly produced

### ISSUE THREAD

**Issue by dennis-wey** [WyriHaximus/github-action-next-semvers#64]
It seems like with version 1.2 the output broke:

Action to reproduce:

```
name: tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  tests:
    runs-on: ubuntu-latest
    name: Run tests

    steps:
      - name: 'Get next minor version'
        id: semvers
        uses: "WyriHaximus/github-action-next-semvers@v1"
        with:
          version: v1.1.1

      - name: Print Output
        run: |
          echo "${{ steps.semvers.outputs.v_patch }}"
          echo "${{ steps.semvers.outputs.patch }}"
          echo "${{ steps.semvers.outputs.v_minor }}"
          echo "${{ steps.semvers.outputs.minor }}"
          echo "${{ steps.semvers.outputs.major }}"
          echo "${{ steps.semvers.outputs.v_major }}"
          echo "${{ toJSON(steps.semvers.outputs) }}"
```
Output I'm getting:
 
![Screenshot 2022-12-19 at 13 35 39](https://user-images.githubusercontent.com/61822363/208427511-02ce644c-9752-4c92-8154-094dabea2800.png)

It seems to me like some quotes weren't correctly escaped while writing the output.
